# Generated by Django 5.2.8 on 2025-12-01 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خبر')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس اینترنتی (Slug)')),
                ('content', models.TextField(verbose_name='متن کامل خبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='تصویر شاخص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='دسته\u200cبندی')),
            ],
        ),
    ]
