# Generated by Django 5.2.8 on 2025-12-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lead',
            field=models.TextField(blank=True, null=True, verbose_name='لید (خلاصه خبر)'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='ویدیو'),
        ),
    ]
